2021-02-22 20:21:34,602 resnet18 INFO: Using 1 GPUS
2021-02-22 20:21:34,603 resnet18 INFO: Namespace(config_file='', opts=[])
2021-02-22 20:21:34,603 resnet18 INFO: Running with config:
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  DATA_NAME: SODA
  ROOT_DIR: /home/wangxiang/dat01/WWX/aiearth/data/enso_round1_train_20210201/
  X_DIM: 72
  Y_DIM: 24
  Z_DIM: 48
DEBUG: False
INPUT:
  
MODEL:
  DEVICE: cuda
  NUM_CLASSES: 2
  PRETRAINED_CMIP: /home/wangxiang/dat01/WWX/aiearth/aiearth_competition/test/usr_data/model_data/best_model.bin
  PRETRAINED_IMAGENET: 
OUTPUT_DIR: /dat01/wangxiang/WWX/aiearth/aiearth_competition/test/usr_data/model_data/soda
SEED: 66
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 1
  COS_CPOCH: 2
  EARLY_STOP_PATIENCE: 20
  IMS_PER_BATCH: 128
  MAX_EPOCHS: 40
  MOMENTUM: 0.9
  OPTIMIZER_NAME: Adam
  SCHEDULER_NAME: CosineAnnealingWarmRestarts
  TRAIN_CHECKPOINT: False
  T_MUL: 2
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0
  WEIGHT_DECAY_BN: 0
TEST:
  IMS_PER_BATCH: 128
  WEIGHT: /dat01/wangxiang/WWX/aiearth/aiearth_competition/test/usr_data/model_data/sodabest-checkpoint.bin
VERBOSE: True
Traceback (most recent call last):
  File "tools/train_net.py", line 81, in <module>
    main()
  File "tools/train_net.py", line 77, in main
    train(cfg, logger)
  File "tools/train_net.py", line 33, in train
    model = build_model(cfg)
  File "./modeling/__init__.py", line 11, in build_model
    model = SimpleResnet(cfg)
  File "./modeling/simpleresnet.py", line 22, in __init__
    self.model.load_state_dict(torch.load(cfg.MODEL.PRETRAINED_CMIP))
  File "/home/wangxiang/.conda/envs/aiearth/lib/python3.8/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/wangxiang/.conda/envs/aiearth/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/wangxiang/.conda/envs/aiearth/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/wangxiang/dat01/WWX/aiearth/aiearth_competition/test/usr_data/model_data/best_model.bin'
